// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: route_guide.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_route_5fguide_2eproto__INCLUDED
#define GRPC_route_5fguide_2eproto__INCLUDED

#include "route_guide.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace gamingstreaming {

// Interface exported by the server.
class GamingStreamingService final {
 public:
  static constexpr char const* service_full_name() {
    return "gamingstreaming.GamingStreamingService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // A Bidirectional streaming RPC.
    //
    // Accepts a stream of RouteNotes sent while a route is being traversed,
    // while receiving other RouteNotes (e.g. from other users).
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>> GamingChannel(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>>(GamingChannelRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>> AsyncGamingChannel(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>>(AsyncGamingChannelRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>> PrepareAsyncGamingChannel(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>>(PrepareAsyncGamingChannelRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // A Bidirectional streaming RPC.
      //
      // Accepts a stream of RouteNotes sent while a route is being traversed,
      // while receiving other RouteNotes (e.g. from other users).
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>* GamingChannelRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>* AsyncGamingChannelRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>* PrepareAsyncGamingChannelRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>> GamingChannel(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>>(GamingChannelRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>> AsyncGamingChannel(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>>(AsyncGamingChannelRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>> PrepareAsyncGamingChannel(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>>(PrepareAsyncGamingChannelRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>* GamingChannelRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>* AsyncGamingChannelRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::gamingstreaming::InputCommand, ::gamingstreaming::FrameSubPacket>* PrepareAsyncGamingChannelRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GamingChannel_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // A Bidirectional streaming RPC.
    //
    // Accepts a stream of RouteNotes sent while a route is being traversed,
    // while receiving other RouteNotes (e.g. from other users).
    virtual ::grpc::Status GamingChannel(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::gamingstreaming::FrameSubPacket, ::gamingstreaming::InputCommand>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_GamingChannel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GamingChannel() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GamingChannel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GamingChannel(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::gamingstreaming::FrameSubPacket, ::gamingstreaming::InputCommand>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGamingChannel(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::gamingstreaming::FrameSubPacket, ::gamingstreaming::InputCommand>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GamingChannel<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GamingChannel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_GamingChannel() {
    }
    ~ExperimentalWithCallbackMethod_GamingChannel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GamingChannel(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::gamingstreaming::FrameSubPacket, ::gamingstreaming::InputCommand>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef ExperimentalWithCallbackMethod_GamingChannel<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GamingChannel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GamingChannel() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GamingChannel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GamingChannel(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::gamingstreaming::FrameSubPacket, ::gamingstreaming::InputCommand>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GamingChannel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GamingChannel() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GamingChannel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GamingChannel(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::gamingstreaming::FrameSubPacket, ::gamingstreaming::InputCommand>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGamingChannel(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GamingChannel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_GamingChannel() {
    }
    ~ExperimentalWithRawCallbackMethod_GamingChannel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GamingChannel(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::gamingstreaming::FrameSubPacket, ::gamingstreaming::InputCommand>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace gamingstreaming


#endif  // GRPC_route_5fguide_2eproto__INCLUDED
