// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

#include "route_guide.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace gamingstreaming {
class FrameSubPacketDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FrameSubPacket>
      _instance;
} _FrameSubPacket_default_instance_;
class InputCommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<InputCommand>
      _instance;
} _InputCommand_default_instance_;
}  // namespace gamingstreaming
namespace protobuf_route_5fguide_2eproto {
static void InitDefaultsFrameSubPacket() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gamingstreaming::_FrameSubPacket_default_instance_;
    new (ptr) ::gamingstreaming::FrameSubPacket();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gamingstreaming::FrameSubPacket::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_FrameSubPacket =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFrameSubPacket}, {}};

static void InitDefaultsInputCommand() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gamingstreaming::_InputCommand_default_instance_;
    new (ptr) ::gamingstreaming::InputCommand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gamingstreaming::InputCommand::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_InputCommand =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsInputCommand}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_FrameSubPacket.base);
  ::google::protobuf::internal::InitSCC(&scc_info_InputCommand.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, frame_number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, packet_number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, pts_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, dts_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, flags_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, mouse_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, mouse_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::FrameSubPacket, mouse_is_visible_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::InputCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::InputCommand, command_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::InputCommand, event_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::InputCommand, key_code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::InputCommand, key_event_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::InputCommand, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::InputCommand, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gamingstreaming::InputCommand, mouse_button_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::gamingstreaming::FrameSubPacket)},
  { 15, -1, sizeof(::gamingstreaming::InputCommand)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::gamingstreaming::_FrameSubPacket_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::gamingstreaming::_InputCommand_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "route_guide.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021route_guide.proto\022\017gamingstreaming\"\276\001\n"
      "\016FrameSubPacket\022\024\n\014frame_number\030\001 \001(\005\022\025\n"
      "\rpacket_number\030\002 \001(\005\022\014\n\004size\030\003 \001(\005\022\013\n\003pt"
      "s\030\004 \001(\003\022\013\n\003dts\030\005 \001(\003\022\r\n\005flags\030\006 \001(\003\022\014\n\004d"
      "ata\030\007 \001(\014\022\017\n\007mouse_x\030\010 \001(\005\022\017\n\007mouse_y\030\t "
      "\001(\005\022\030\n\020mouse_is_visible\030\n \001(\010\"\211\001\n\014InputC"
      "ommand\022\017\n\007command\030\001 \001(\t\022\022\n\nevent_type\030\002 "
      "\001(\005\022\020\n\010key_code\030\003 \001(\005\022\026\n\016key_event_type\030"
      "\004 \001(\005\022\t\n\001x\030\005 \001(\005\022\t\n\001y\030\006 \001(\005\022\024\n\014mouse_but"
      "ton\030\007 \001(\0052o\n\026GamingStreamingService\022U\n\rG"
      "amingChannel\022\035.gamingstreaming.InputComm"
      "and\032\037.gamingstreaming.FrameSubPacket\"\000(\001"
      "0\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 490);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "route_guide.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_route_5fguide_2eproto
namespace gamingstreaming {

// ===================================================================

void FrameSubPacket::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FrameSubPacket::kFrameNumberFieldNumber;
const int FrameSubPacket::kPacketNumberFieldNumber;
const int FrameSubPacket::kSizeFieldNumber;
const int FrameSubPacket::kPtsFieldNumber;
const int FrameSubPacket::kDtsFieldNumber;
const int FrameSubPacket::kFlagsFieldNumber;
const int FrameSubPacket::kDataFieldNumber;
const int FrameSubPacket::kMouseXFieldNumber;
const int FrameSubPacket::kMouseYFieldNumber;
const int FrameSubPacket::kMouseIsVisibleFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FrameSubPacket::FrameSubPacket()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_route_5fguide_2eproto::scc_info_FrameSubPacket.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:gamingstreaming.FrameSubPacket)
}
FrameSubPacket::FrameSubPacket(const FrameSubPacket& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.data().size() > 0) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  ::memcpy(&frame_number_, &from.frame_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&mouse_is_visible_) -
    reinterpret_cast<char*>(&frame_number_)) + sizeof(mouse_is_visible_));
  // @@protoc_insertion_point(copy_constructor:gamingstreaming.FrameSubPacket)
}

void FrameSubPacket::SharedCtor() {
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&frame_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mouse_is_visible_) -
      reinterpret_cast<char*>(&frame_number_)) + sizeof(mouse_is_visible_));
}

FrameSubPacket::~FrameSubPacket() {
  // @@protoc_insertion_point(destructor:gamingstreaming.FrameSubPacket)
  SharedDtor();
}

void FrameSubPacket::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FrameSubPacket::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* FrameSubPacket::descriptor() {
  ::protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FrameSubPacket& FrameSubPacket::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_route_5fguide_2eproto::scc_info_FrameSubPacket.base);
  return *internal_default_instance();
}


void FrameSubPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:gamingstreaming.FrameSubPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&frame_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mouse_is_visible_) -
      reinterpret_cast<char*>(&frame_number_)) + sizeof(mouse_is_visible_));
  _internal_metadata_.Clear();
}

bool FrameSubPacket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gamingstreaming.FrameSubPacket)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 frame_number = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &frame_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 packet_number = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &packet_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 size = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 pts = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &pts_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 dts = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &dts_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 flags = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &flags_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes data = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 mouse_x = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mouse_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 mouse_y = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mouse_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool mouse_is_visible = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &mouse_is_visible_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gamingstreaming.FrameSubPacket)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gamingstreaming.FrameSubPacket)
  return false;
#undef DO_
}

void FrameSubPacket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gamingstreaming.FrameSubPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 frame_number = 1;
  if (this->frame_number() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->frame_number(), output);
  }

  // int32 packet_number = 2;
  if (this->packet_number() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->packet_number(), output);
  }

  // int32 size = 3;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->size(), output);
  }

  // int64 pts = 4;
  if (this->pts() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->pts(), output);
  }

  // int64 dts = 5;
  if (this->dts() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->dts(), output);
  }

  // int64 flags = 6;
  if (this->flags() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(6, this->flags(), output);
  }

  // bytes data = 7;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      7, this->data(), output);
  }

  // int32 mouse_x = 8;
  if (this->mouse_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->mouse_x(), output);
  }

  // int32 mouse_y = 9;
  if (this->mouse_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->mouse_y(), output);
  }

  // bool mouse_is_visible = 10;
  if (this->mouse_is_visible() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->mouse_is_visible(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:gamingstreaming.FrameSubPacket)
}

::google::protobuf::uint8* FrameSubPacket::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gamingstreaming.FrameSubPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 frame_number = 1;
  if (this->frame_number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->frame_number(), target);
  }

  // int32 packet_number = 2;
  if (this->packet_number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->packet_number(), target);
  }

  // int32 size = 3;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->size(), target);
  }

  // int64 pts = 4;
  if (this->pts() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->pts(), target);
  }

  // int64 dts = 5;
  if (this->dts() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->dts(), target);
  }

  // int64 flags = 6;
  if (this->flags() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(6, this->flags(), target);
  }

  // bytes data = 7;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        7, this->data(), target);
  }

  // int32 mouse_x = 8;
  if (this->mouse_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->mouse_x(), target);
  }

  // int32 mouse_y = 9;
  if (this->mouse_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->mouse_y(), target);
  }

  // bool mouse_is_visible = 10;
  if (this->mouse_is_visible() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->mouse_is_visible(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gamingstreaming.FrameSubPacket)
  return target;
}

size_t FrameSubPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gamingstreaming.FrameSubPacket)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes data = 7;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  // int32 frame_number = 1;
  if (this->frame_number() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->frame_number());
  }

  // int32 packet_number = 2;
  if (this->packet_number() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->packet_number());
  }

  // int64 pts = 4;
  if (this->pts() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->pts());
  }

  // int64 dts = 5;
  if (this->dts() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->dts());
  }

  // int32 size = 3;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->size());
  }

  // int32 mouse_x = 8;
  if (this->mouse_x() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mouse_x());
  }

  // int64 flags = 6;
  if (this->flags() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->flags());
  }

  // int32 mouse_y = 9;
  if (this->mouse_y() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mouse_y());
  }

  // bool mouse_is_visible = 10;
  if (this->mouse_is_visible() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FrameSubPacket::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gamingstreaming.FrameSubPacket)
  GOOGLE_DCHECK_NE(&from, this);
  const FrameSubPacket* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FrameSubPacket>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gamingstreaming.FrameSubPacket)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gamingstreaming.FrameSubPacket)
    MergeFrom(*source);
  }
}

void FrameSubPacket::MergeFrom(const FrameSubPacket& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gamingstreaming.FrameSubPacket)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.frame_number() != 0) {
    set_frame_number(from.frame_number());
  }
  if (from.packet_number() != 0) {
    set_packet_number(from.packet_number());
  }
  if (from.pts() != 0) {
    set_pts(from.pts());
  }
  if (from.dts() != 0) {
    set_dts(from.dts());
  }
  if (from.size() != 0) {
    set_size(from.size());
  }
  if (from.mouse_x() != 0) {
    set_mouse_x(from.mouse_x());
  }
  if (from.flags() != 0) {
    set_flags(from.flags());
  }
  if (from.mouse_y() != 0) {
    set_mouse_y(from.mouse_y());
  }
  if (from.mouse_is_visible() != 0) {
    set_mouse_is_visible(from.mouse_is_visible());
  }
}

void FrameSubPacket::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gamingstreaming.FrameSubPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FrameSubPacket::CopyFrom(const FrameSubPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gamingstreaming.FrameSubPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FrameSubPacket::IsInitialized() const {
  return true;
}

void FrameSubPacket::Swap(FrameSubPacket* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FrameSubPacket::InternalSwap(FrameSubPacket* other) {
  using std::swap;
  data_.Swap(&other->data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(frame_number_, other->frame_number_);
  swap(packet_number_, other->packet_number_);
  swap(pts_, other->pts_);
  swap(dts_, other->dts_);
  swap(size_, other->size_);
  swap(mouse_x_, other->mouse_x_);
  swap(flags_, other->flags_);
  swap(mouse_y_, other->mouse_y_);
  swap(mouse_is_visible_, other->mouse_is_visible_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata FrameSubPacket::GetMetadata() const {
  protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void InputCommand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int InputCommand::kCommandFieldNumber;
const int InputCommand::kEventTypeFieldNumber;
const int InputCommand::kKeyCodeFieldNumber;
const int InputCommand::kKeyEventTypeFieldNumber;
const int InputCommand::kXFieldNumber;
const int InputCommand::kYFieldNumber;
const int InputCommand::kMouseButtonFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

InputCommand::InputCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_route_5fguide_2eproto::scc_info_InputCommand.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:gamingstreaming.InputCommand)
}
InputCommand::InputCommand(const InputCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.command().size() > 0) {
    command_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.command_);
  }
  ::memcpy(&event_type_, &from.event_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&mouse_button_) -
    reinterpret_cast<char*>(&event_type_)) + sizeof(mouse_button_));
  // @@protoc_insertion_point(copy_constructor:gamingstreaming.InputCommand)
}

void InputCommand::SharedCtor() {
  command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&event_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mouse_button_) -
      reinterpret_cast<char*>(&event_type_)) + sizeof(mouse_button_));
}

InputCommand::~InputCommand() {
  // @@protoc_insertion_point(destructor:gamingstreaming.InputCommand)
  SharedDtor();
}

void InputCommand::SharedDtor() {
  command_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void InputCommand::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* InputCommand::descriptor() {
  ::protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const InputCommand& InputCommand::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_route_5fguide_2eproto::scc_info_InputCommand.base);
  return *internal_default_instance();
}


void InputCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:gamingstreaming.InputCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  command_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&event_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mouse_button_) -
      reinterpret_cast<char*>(&event_type_)) + sizeof(mouse_button_));
  _internal_metadata_.Clear();
}

bool InputCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gamingstreaming.InputCommand)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string command = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_command()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->command().data(), static_cast<int>(this->command().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "gamingstreaming.InputCommand.command"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 event_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &event_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 key_code = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &key_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 key_event_type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &key_event_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 x = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 y = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 mouse_button = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mouse_button_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gamingstreaming.InputCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gamingstreaming.InputCommand)
  return false;
#undef DO_
}

void InputCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gamingstreaming.InputCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string command = 1;
  if (this->command().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->command().data(), static_cast<int>(this->command().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gamingstreaming.InputCommand.command");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->command(), output);
  }

  // int32 event_type = 2;
  if (this->event_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->event_type(), output);
  }

  // int32 key_code = 3;
  if (this->key_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->key_code(), output);
  }

  // int32 key_event_type = 4;
  if (this->key_event_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->key_event_type(), output);
  }

  // int32 x = 5;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->x(), output);
  }

  // int32 y = 6;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->y(), output);
  }

  // int32 mouse_button = 7;
  if (this->mouse_button() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->mouse_button(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:gamingstreaming.InputCommand)
}

::google::protobuf::uint8* InputCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gamingstreaming.InputCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string command = 1;
  if (this->command().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->command().data(), static_cast<int>(this->command().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gamingstreaming.InputCommand.command");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->command(), target);
  }

  // int32 event_type = 2;
  if (this->event_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->event_type(), target);
  }

  // int32 key_code = 3;
  if (this->key_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->key_code(), target);
  }

  // int32 key_event_type = 4;
  if (this->key_event_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->key_event_type(), target);
  }

  // int32 x = 5;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->x(), target);
  }

  // int32 y = 6;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->y(), target);
  }

  // int32 mouse_button = 7;
  if (this->mouse_button() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->mouse_button(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gamingstreaming.InputCommand)
  return target;
}

size_t InputCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gamingstreaming.InputCommand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string command = 1;
  if (this->command().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->command());
  }

  // int32 event_type = 2;
  if (this->event_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->event_type());
  }

  // int32 key_code = 3;
  if (this->key_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->key_code());
  }

  // int32 key_event_type = 4;
  if (this->key_event_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->key_event_type());
  }

  // int32 x = 5;
  if (this->x() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->x());
  }

  // int32 y = 6;
  if (this->y() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->y());
  }

  // int32 mouse_button = 7;
  if (this->mouse_button() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mouse_button());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InputCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gamingstreaming.InputCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const InputCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const InputCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gamingstreaming.InputCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gamingstreaming.InputCommand)
    MergeFrom(*source);
  }
}

void InputCommand::MergeFrom(const InputCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gamingstreaming.InputCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.command().size() > 0) {

    command_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.command_);
  }
  if (from.event_type() != 0) {
    set_event_type(from.event_type());
  }
  if (from.key_code() != 0) {
    set_key_code(from.key_code());
  }
  if (from.key_event_type() != 0) {
    set_key_event_type(from.key_event_type());
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.mouse_button() != 0) {
    set_mouse_button(from.mouse_button());
  }
}

void InputCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gamingstreaming.InputCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InputCommand::CopyFrom(const InputCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gamingstreaming.InputCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InputCommand::IsInitialized() const {
  return true;
}

void InputCommand::Swap(InputCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void InputCommand::InternalSwap(InputCommand* other) {
  using std::swap;
  command_.Swap(&other->command_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(event_type_, other->event_type_);
  swap(key_code_, other->key_code_);
  swap(key_event_type_, other->key_event_type_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(mouse_button_, other->mouse_button_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata InputCommand::GetMetadata() const {
  protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace gamingstreaming
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::gamingstreaming::FrameSubPacket* Arena::CreateMaybeMessage< ::gamingstreaming::FrameSubPacket >(Arena* arena) {
  return Arena::CreateInternal< ::gamingstreaming::FrameSubPacket >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::gamingstreaming::InputCommand* Arena::CreateMaybeMessage< ::gamingstreaming::InputCommand >(Arena* arena) {
  return Arena::CreateInternal< ::gamingstreaming::InputCommand >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
