language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
#      compiler: clang
    - os: linux
      dist: bionic

before_install:
  # MACOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      bash $TRAVIS_BUILD_DIR/scripts/install_deps_macos.sh;
    fi
  # LINUX
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      bash $TRAVIS_BUILD_DIR/scripts/install_deps_linux.sh;
    fi
script:
  - mkdir -p build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export TOOLCHAIN_ARG="-DCMAKE_TOOLCHAIN_FILE=/Users/travis/vcpkg/scripts/buildsystems/vcpkg.cmake";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export TOOLCHAIN_ARG="-DCMAKE_TOOLCHAIN_FILE=/home/travis/vcpkg/scripts/buildsystems/vcpkg.cmake";
    fi
  - cmake "$TOOLCHAIN_ARG" ..
  - cmake --build .

cache:
  directories:
  - $HOME/travis_cache
