language: cpp
matrix:
  include:
    - os: osx
          env: WORDSIZE=64 CONFIGURATION=Debug
          osx_image: xcode7.3
    compiler: clang
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install libav; fi
script:
  - |
    mkdir build
    pushd build
    cmake ..
    make all
    make install
    popd
