# Specify version format
version: "1.0.0.{build}"

# Image to use
image: Visual Studio 2017

# Build matrix
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_COMPILER: Visual Studio 15 2017
      CMAKE_COMPILER_TARGET: host=x64
      CMAKE_SYSTEM_VERSION: 10.0.16299.91
      CPACK_SYSTEM_NAME: win32
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      CMAKE_COMPILER: Visual Studio 15 2017 Win64
#      CMAKE_COMPILER_TARGET: host=x64
#      CMAKE_SYSTEM_VERSION: 10.0.16299.91
#      CPACK_SYSTEM_NAME: win64

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive
  - nuget install SDL2 -OutputDirectory deps -ExcludeVersion -NoCache
  - nuget install FFmpeg.Nightly -OutputDirectory deps -ExcludeVersion -NoCache

before_build:
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_COMPILER%" -T "%CMAKE_COMPILER_TARGET%" -DCMAKE_SYSTEM_VERSION="%CMAKE_SYSTEM_VERSION%" -DCMAKE_INSTALL_PREFIX="%CD%/distrib" -DCPACK_GENERATOR="7Z;ZIP" -DCPACK_SYSTEM_NAME="%CPACK_SYSTEM_NAME%" ..

build_script:
  - cmake --build . --config RelWithDebInfo

# Test scripts
test: off
